# permissions for end users to view clustersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustersecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operators
    app.kubernetes.io/part-of: k8s-operators
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-viewer-role
rules:
  - apiGroups:
      - k8soperators.cmg.io
    resources:
      - clustersecrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - k8soperators.cmg.io
    resources:
      - clustersecrets/status
    verbs:
      - get
