apiVersion: k8s-operators.cmgsj.github.io.cmgsj.github.io/v1alpha1
kind: ClusterSecret
metadata:
  labels:
    app.kubernetes.io/name: k8s-operators
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-sample
spec:
  # TODO(user): Add fields here
