apiVersion: k8soperators.cmg.io/v1alpha1
kind: ClusterSecret
metadata:
  name: my-secret
spec:
  type: Opaque
  namespaces:
    include:
      selector: {}
    exclude:
      names:
        - default
  data:
    username: YWRtaW4=
    password: cGFzc3dvcmQ=
